$font = BerkeleyMono Nerd Font

general {
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 280, 50
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 1
    rounding = 10
    outer_color = rgba(928374cc)
    inner_color = rgba(1d2021cc)
    font_color = rgb(ebdbb2)
    placeholder_text = <i>Password...</i>
    fade_on_empty = false
    fail_color = rgba(fb4934ee)
    fail_text = <i>Incorrect</i>
    check_color = rgba(b8bb26ee)
    capslock_color = rgba(fabd2fff)
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = rgb(ebdbb2)
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A %d %B %Y')"
    font_size = 22
    font_family = $font
    color = rgb(928374)
    position = 0, 100
    halign = center
    valign = center
}
