#!/usr/bin/env bash

lock="<span font='Symbols Nerd Font 13' color='#83a598'>󰌾</span>   Lock"

logout="<span font='Symbols Nerd Font 13' color='#fe8019'>󰍃</span>   Logout"
reboot="<span font='Symbols Nerd Font 13' color='#b8bb26'>󰜉</span>   Reboot"
shutdown="<span font='Symbols Nerd Font 13' color='#fb4934'>󰐥</span>   Shutdown"

chosen=$(echo -e "$lock\n$logout\n$reboot\n$shutdown" | rofi \
    -dmenu \
    -markup-rows \
    -p "" \
    -theme ~/.config/rofi/powermenu.rasi)

case "$chosen" in
    *Lock)     loginctl lock-session ;;

    *Logout)   loginctl terminate-session "$XDG_SESSION_ID" ;;
    *Reboot)   systemctl reboot ;;
    *Shutdown) systemctl poweroff ;;
esac
