onboarding = false

[theme]
name = "gruvbox"

[ui]
agent_panel_sort = "priority"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "open lazygit"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+alt+y"
type = "popup"
command = "yazi"
description = "open file browser"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer"
description = "open file viewer in split"

[[keys.command]]
key = "prefix+shift+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer-tab"
description = "open file viewer in tab"
